name: Build and Deploy (Self-Hosted Secure)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Build and Deploy Docker Container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Build and deploy container
        run: |
          docker compose up --build --no-cache -d
          docker compose --env-file .env down || true
          docker compose --env-file .env up -d
